package samza.examples.sql.test;

/**
 * Created by liudp on 2016/3/3.
 */
public class Datas {

    public static final String[][] msgs3Cols = new String[][]{
            {"1111", "Word1", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj1"},
            {"2222", "Word2", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2"},
            {"3333", "Word3", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj3"},
            {"4444", "Word4", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj4"},
            {"5555", "Word5", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj5"},
            {"6666", "Word6", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj6"},
            {"7777", "Word7", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj7"},
            {"8888", "Word8", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj8"},
            {"9999", "Word9", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj9"},
            {"99990", "Word90", "Abcdefghijklmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj90"}
    };
    public static final String[][] msgsUrlRz = new String[][]{
            {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_0",
            "1111110",
            "1111110",
            "1111110",
            "1111110",
            "1111110",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_0",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_0",
            "jjjdldz_ip1_0",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_0",
            "jjjjjjjjdllx1_0",
            "jjjbz1_0",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_0",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_0",
            "jjyl11_0",
            "jjyl21_0",
            "jjjjjjjjjjjjjjjjjjjjjyl31_0",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_0",
            "jjjjjjjjjjjjjjjjjjjyl51_0",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_1",
            "1111111",
            "1111111",
            "1111111",
            "1111111",
            "1111111",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_1",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_1",
            "jjjdldz_ip1_1",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_1",
            "jjjjjjjjdllx1_1",
            "jjjbz1_1",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_1",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_1",
            "jjyl11_1",
            "jjyl21_1",
            "jjjjjjjjjjjjjjjjjjjjjyl31_1",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_1",
            "jjjjjjjjjjjjjjjjjjjyl51_1",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_2",
            "1111112",
            "1111112",
            "1111112",
            "1111112",
            "1111112",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_2",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_2",
            "jjjdldz_ip1_2",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_2",
            "jjjjjjjjdllx1_2",
            "jjjbz1_2",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_2",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_2",
            "jjyl11_2",
            "jjyl21_2",
            "jjjjjjjjjjjjjjjjjjjjjyl31_2",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_2",
            "jjjjjjjjjjjjjjjjjjjyl51_2",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_3",
            "1111113",
            "1111113",
            "1111113",
            "1111113",
            "1111113",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_3",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_3",
            "jjjdldz_ip1_3",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_3",
            "jjjjjjjjdllx1_3",
            "jjjbz1_3",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_3",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_3",
            "jjyl11_3",
            "jjyl21_3",
            "jjjjjjjjjjjjjjjjjjjjjyl31_3",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_3",
            "jjjjjjjjjjjjjjjjjjjyl51_3",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_4",
            "1111114",
            "1111114",
            "1111114",
            "1111114",
            "1111114",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_4",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_4",
            "jjjdldz_ip1_4",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_4",
            "jjjjjjjjdllx1_4",
            "jjjbz1_4",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_4",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_4",
            "jjyl11_4",
            "jjyl21_4",
            "jjjjjjjjjjjjjjjjjjjjjyl31_4",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_4",
            "jjjjjjjjjjjjjjjjjjjyl51_4",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_5",
            "1111115",
            "1111115",
            "1111115",
            "1111115",
            "1111115",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_5",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_5",
            "jjjdldz_ip1_5",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_5",
            "jjjjjjjjdllx1_5",
            "jjjbz1_5",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_5",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_5",
            "jjyl11_5",
            "jjyl21_5",
            "jjjjjjjjjjjjjjjjjjjjjyl31_5",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_5",
            "jjjjjjjjjjjjjjjjjjjyl51_5",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_6",
            "1111116",
            "1111116",
            "1111116",
            "1111116",
            "1111116",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_6",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_6",
            "jjjdldz_ip1_6",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_6",
            "jjjjjjjjdllx1_6",
            "jjjbz1_6",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_6",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_6",
            "jjyl11_6",
            "jjyl21_6",
            "jjjjjjjjjjjjjjjjjjjjjyl31_6",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_6",
            "jjjjjjjjjjjjjjjjjjjyl51_6",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_7",
            "1111117",
            "1111117",
            "1111117",
            "1111117",
            "1111117",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_7",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_7",
            "jjjdldz_ip1_7",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_7",
            "jjjjjjjjdllx1_7",
            "jjjbz1_7",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_7",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_7",
            "jjyl11_7",
            "jjyl21_7",
            "jjjjjjjjjjjjjjjjjjjjjyl31_7",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_7",
            "jjjjjjjjjjjjjjjjjjjyl51_7",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_8",
            "1111118",
            "1111118",
            "1111118",
            "1111118",
            "1111118",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_8",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_8",
            "jjjdldz_ip1_8",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_8",
            "jjjjjjjjdllx1_8",
            "jjjbz1_8",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_8",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_8",
            "jjyl11_8",
            "jjyl21_8",
            "jjjjjjjjjjjjjjjjjjjjjyl31_8",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_8",
            "jjjjjjjjjjjjjjjjjjjyl51_8",
    }
            , {
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjshijian1_9",
            "1111119",
            "1111119",
            "1111119",
            "1111119",
            "1111119",
            "jjjjjjjjjjjjjjjjjjjjmd_dz1_9",
            "jjjjjjjjjjjjjjjjjjjjjjjjfd_lj1_9",
            "jjjdldz_ip1_9",
            "jjjjjjjjjjjjjjjjjjjjjjjdldk1_9",
            "jjjjjjjjdllx1_9",
            "jjjbz1_9",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjclj_ip1_9",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjyl1_9",
            "jjyl11_9",
            "jjyl21_9",
            "jjjjjjjjjjjjjjjjjjjjjyl31_9",
            "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyl41_9",
            "jjjjjjjjjjjjjjjjjjjyl51_9",
    }


    };

}
